version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=canions_db
      - DB_USER=canions_user
      - DB_PASSWORD=canions_pass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=canions_db
      - POSTGRES_USER=canions_user
      - POSTGRES_PASSWORD=canions_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data:
