# Generated by Django 5.0.5 on 2025-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='observations/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='medias',
            field=models.ManyToManyField(through='canionsDoSul_app.ObservationMedia', to='canionsDoSul_app.media'),
        ),
    ]
