# Generated by Django 5.0.5 on 2025-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='family',
            table='family',
        ),
        migrations.AlterModelTable(
            name='genus',
            table='genus',
        ),
        migrations.AlterModelTable(
            name='localization',
            table='localization',
        ),
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='observation',
        ),
        migrations.AlterModelTable(
            name='observationmedia',
            table='observation_media',
        ),
        migrations.AlterModelTable(
            name='scientist',
            table='scientist',
        ),
        migrations.AlterModelTable(
            name='specialist',
            table='specialist',
        ),
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
