# Generated by Django 5.0.5 on 2025-05-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0002_remove_media_path_media_image_observation_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='country_name',
            field=models.CharField(default='Brasil', max_length=255),
        ),
    ]
