# Generated by Django 5.0.5 on 2025-05-15 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0003_localization_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canionsDoSul_app.localization'),
        ),
    ]
