# Generated by Django 5.0.5 on 2025-05-18 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0004_alter_observation_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canionsDoSul_app.species'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(default='pendente', max_length=100),
        ),
    ]
