# Generated by Django 5.0.5 on 2025-06-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0005_alter_observation_species_alter_observation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='files',
            field=models.FileField(default='default.jpg', upload_to='observations/'),
            preserve_default=False,
        ),
    ]
