# Generated by Django 5.0.5 on 2025-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0006_remove_media_image_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='files',
            field=models.FileField(default='default.jpg', upload_to='observations/'),
        ),
    ]
