# Generated by Django 5.0.5 on 2025-06-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0007_alter_media_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='habitat',
            field=models.CharField(max_length=2000),
        ),
    ]
