# Generated by Django 5.0.5 on 2025-06-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0008_alter_species_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
