# Generated by Django 5.0.5 on 2025-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0009_alter_family_name_alter_genus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='habitat',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
