# Generated by Django 5.0.5 on 2025-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0010_observation_notes_alter_species_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
