# Generated by Django 5.0.5 on 2025-06-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0011_alter_observation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='popular_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
