# Generated by Django 5.0.5 on 2025-07-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0012_alter_species_popular_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together={('city_name', 'state_name', 'country_name')},
        ),
    ]
