# Generated by Django 5.0.5 on 2025-07-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canionsDoSul_app', '0013_alter_localization_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together=set(),
        ),
    ]
