# BLOCO 1 - HTTP (porta 80)
server {
    listen 80;
    server_name faunasul.com.br www.faunasul.com.br;

    # Serve os arquivos de desafio do Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireciona tudo para HTTPS (após o certificado estar pronto)
    location / {
        return 301 https://$host$request_uri;
    }
}

# BLOCO 2 - HTTPS (porta 443)
server {
    listen 443 ssl;
    server_name faunasul.com.br www.faunasul.com.br;

    ssl_certificate /etc/letsencrypt/live/faunasul.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/faunasul.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
       proxy_pass http://web:8000/;
      proxy_set_header Host $host;
     proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /canions/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /canions/media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    client_max_body_size 100M;
}

#funcionando em prod
#server {
#    listen 80;
#    server_name 31.220.102.180;
#
#    location / {
#        proxy_pass http://web:8000/;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#    }
#
#    location /static/ {
#        alias /canions/staticfiles/;
#        expires 30d;
#        add_header Cache-Control "public, immutable";
#    }
#
#    location /media/ {
#        alias /canions/media/;
#        expires 30d;
#        add_header Cache-Control "public, immutable";
#    }
#
#    client_max_body_size 100M;
#}


#Original
# server {
#     listen 80;
#     server_name 31.220.102.180;

#     location /static/ {
#         alias /canions/staticfiles/;
#     }

#     location /media/ {
#         alias /canions/media/;
#     }

#     location / {
#         proxy_pass http://web:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }
