server {
    listen 80;
    server_name faunasul.com.br www.faunasul.com.br;

    location / {
        proxy_pass http://web:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /canions/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /canions/media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    client_max_body_size 100M;
}


#Original
# server {
#     listen 80;
#     server_name 31.220.102.180;

#     location /static/ {
#         alias /canions/staticfiles/;
#     }

#     location /media/ {
#         alias /canions/media/;
#     }

#     location / {
#         proxy_pass http://web:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }
