version = 4.1.1
archive_dir = /etc/letsencrypt/archive/faunasul.com.br
cert = /etc/letsencrypt/live/faunasul.com.br/cert.pem
privkey = /etc/letsencrypt/live/faunasul.com.br/privkey.pem
chain = /etc/letsencrypt/live/faunasul.com.br/chain.pem
fullchain = /etc/letsencrypt/live/faunasul.com.br/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 08708eb203fc22b459895ed2c8b71cba
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
faunasul.com.br = /var/www/certbot
www.faunasul.com.br = /var/www/certbot
